openapi: "3.0.0"
info:
  title: Cash Register App
  description: App for a cash register
  version: 1.0.0

paths:
    /cashregister/change/:
        post:
            summary: "Submits purchases and payments for change calculation"
            requestBody:
                required: True
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ChangeRequest'
            responses:
                "200":
                    description: Response after successful change processing
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ChangeResponse"
        
components:
    schemas:
                      
        ChangeRequest:
            required:
              - purchasePrice
              - paymentAmount
              - billCounts
              - totalBills
            properties:
                purchasePrice:
                    type: number
                paymentAmount:
                    type: number
                billCounts:
                    type: array
                    items:
                      type: integer
                totalBills:
                    type: integer
                    
        
        ChangeResponse:
            required:
                - change
            properties:
                change:
                    type: array
                    items:
                      type: number
        
